### ISSUE TITLE
New container for the latest version of BIDScoin

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#101]
I will create a container with the newest version of BIDScoin. The name of the container will be bidscoin rather than bidstools because I want the version number to be included in the container name. The reason is that there are different versions of BIDScoin, and it is important for people to know which are available in Neurodesk (because some features are only included in the the latest versions).
I aim to do it by the 5/3/22

**Comment by stebo85** [comment]
ok, great!

**Comment by civier** [comment]
@stebo85 @aswinnarayanan I'm working on the container now. Can you please pull-in the latest changes from Neurodocker upstream into our fork of Neurodocker?

**Comment by stebo85** [comment]
Dear @civier - I updated it from upstream. However, you could have done this yourself - just click on fetch upstream in the neurodocker fork.

**Comment by civier** [comment]
Ah, ok. I just followed the instructions in point 1.2 here https://neurodesk.github.io/developers/new_tools/add_tool/#build-container
that say to contact one of the admins.

I then went here https://github.com/orgs/NeuroDesk/people?query=role%3Aowner
and saw that I'm not one of the owners.

So I guess that 'owner' and 'admin' are different, but how can a user see who are the admins?

**Comment by aswinnarayanan** [comment]
Hi @civier, that is the organisation level permission.
You and @DavidjWhite33 have admin roles on NeuroDesk/neurodocker and write roles on NeuroDesk/neurocontainers repositories.
It should be visible here https://github.com/NeuroDesk/neurocontainers/settings/access

**Comment by civier** [comment]
Hi @aswinnarayanan 
When I go to think link it tells me that I'm entering sudo mode and ask for my password, so I don't think this is something users would be able to access. Am I right?

**Comment by civier** [comment]
In any case, wouldn't it be easier to simply ask users to post a request in Neurodesk' Discussion form if they want neurodocker to be synched?

**Comment by aswinnarayanan** [comment]
> In any case, wouldn't it be easier to simply ask users to post a request in Neurodesk' Discussion form if they want neurodocker to be synched?

That's what the instructions already say at https://neurodesk.github.io/developers/new_tools/add_tool/#build-container

But you're one of the NeuroDesk/neurodocker admins, so you don't have to follow the user procedure

**Comment by stebo85** [comment]
completed.
