### ISSUE TITLE
Add sigviewer

### ISSUE THREAD

**Issue by TomEmotion** [NeuroDesk/neurocontainers#105]
Add sigviewer:
https://github.com/cbrnr/sigviewer

Viewer for EEG/MEG time series data.

**Comment by TomEmotion** [comment]
Will do this myself - how do I assign this to myself?

**Comment by stebo85** [comment]
that would be super cool and should be very easy to add: https://launchpad.net/ubuntu/+source/sigviewer I would use https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/datalad/build.sh as a starting point and then it should just install as a normal package :)

**Comment by stebo85** [comment]
there should be a little button to do this? 
![image](https://user-images.githubusercontent.com/4021595/157609098-2bbf002f-3651-45d3-80da-16d96afe4459.png)

**Comment by TomEmotion** [comment]
No, I don't have any of the gear wheels down the side.

**Comment by stebo85** [comment]
i added you to the repo as Maintainer, can you try again?

**Comment by TomEmotion** [comment]
Fixed - thanks!

**Comment by TomEmotion** [comment]
So a final hiccup - the container worked within Neurodesktop when I dowloaded it manually, but does not load from the menu now that Sigviewer is in the current Neurodesktop release.

I don't know if it's related to this:
In the build script, @stebo85 you commented to not expose the whole /usr/bin directory, and deleted that line I think. I understand the rationale, but what's the option when the software installation (using apt or yum) puts the binary into /usr/bin, rather than, say, /opt/sigviewer/bin ?

Sorry for the noobie questions, but promise I'm a quick learner.

**Comment by stebo85** [comment]
ok, thank you for finding this. I am investigating the problem now.

I don't think it's related to removing `--env DEPLOY_PATH=/usr/bin/` because it only requires this or '--env DEPLOY_BINS=${toolName}' - DEPLOY_PATH will release ALL binaries, DEPLOY_BINS only a list of specified binaries that are on the $path

**Comment by stebo85** [comment]
found the problem @TomEmotion 

the version number of sigviewer was "0.6.4-1" - the -1 was the problem because it's used to separate fields in the strings. I now fixed it and will push the changes through.

Thank you again for checking and finding this problem.

Cheers
Steffen

**Comment by stebo85** [comment]
Tested and working in vnmd/neurodesktop:20220315
