### ISSUE TITLE
Add NiftyReg

### ISSUE THREAD

**Issue by emmabiondetti** [NeuroDesk/neurocontainers#106]
Add NiftyReg:
https://github.com/KCL-BMEIS/niftyreg

NiftyReg is open-source software for rigid, affine and non-linear registration of nifti or analyse images.

**Comment by stebo85** [comment]
--workdir=/opt/niftyreg-builder \
   --run="curl -fsSL --retry 5 https://github.com/KCL-BMEIS/niftyreg/archive/${niftyreg_commit_sha}.tar.gz | tar -xz -C ./" \
   --run="mv niftyreg-${niftyreg_commit_sha} src && mkdir build" \
   --run="cmake -S src -B build -D CMAKE_INSTALL_PREFIX=/opt/niftyreg-${niftyreg_version}" \
   --run="cd build && make && make install" \

**Comment by stebo85** [comment]
Dear @emmabiondetti 

niftyreg is now included in neurodesk version "20220317" -  can you test and let me know if it works as expected?

Cheers
Steffen

**Comment by emmabiondetti** [comment]
Dear Steffen,

I have tested the installation of niftyreg, and it all works fine.

Thanks,
Emma

**Comment by stebo85** [comment]
Thank you so much :)
