### ISSUE TITLE
MNE Python (update) and MNE BIDS Pipeline

### ISSUE THREAD

**Issue by DavidjWhite33** [NeuroDesk/neurocontainers#107]
The MNE BIDS Pipeline (https://github.com/mne-tools/mne-bids-pipeline/) has some additional dependencies to the current MNE conda environment. There is a version of the MNE BIDS Pipeline from around the time of the current MNE release (0.24.1), and I will create a container with this MNE version, the extra dependencies, and the Pipeline scripts. 

Moving forward, it looks like the MNE BIDS Pipeline is tested with the development version of MNE Python and MNE BIDS, so one solution to this is to maintain a container with the current release version of MNE Python, and then have a separate separate container which has these development versions to support the MNE BIDS Pipeline.

@air2310 I'll just test this locally today, so just let me know if there's any issues before I push any changes in the coming days

**Comment by stebo85** [comment]
cool - that's great :) Thank you for looking into this

**Comment by air2310** [comment]
Thanks for the heads up @DavidjWhite33 - I've never used it before and hand't realised it wasn't working. I can't forsee any isues with having the two separate containers as long as they're clearly named :)

**Comment by DavidjWhite33** [comment]
MNE Python have now released a version 1.0.0. This version works with the MNE BIDS Pipeline, so I've put both the MNE 1.0.0 conda env and extra dependencies for MNE BIDS Pipeline code together. These extra dependencies are in the mne-starter.yml in my forked 'condaenvs', and can merge if everyone is happy for these to be added to the mne conda environment.

**Comment by stebo85** [comment]
Thank you :)
