### ISSUE TITLE
Support for Neurodocker Version 0.8.0

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurocontainers#109]
Neurodocker refactor released (v0.8.0) https://github.com/ReproNim/neurodocker/releases/tag/0.8.0

**Comment by stebo85** [comment]
As far as I know we updated already most recipes to use the v0.8.0 syntax as we have been using the master tree since a while. A few things changed around miniconda and I fixed the occurences that I knew of

**Comment by aswinnarayanan** [comment]
No worries then. Closing
