### ISSUE TITLE
add qmrlab via octave

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#121]
qMRLab can work via octave https://qmrlab.readthedocs.io/en/master/install.html#qmrlab-in-octave

**Comment by Vbitz** [comment]
Seems to be a good first step for the container build system.

Compiles fine with the command line `tinyrange login octave -a https://github.com/qMRLab/qMRLab/archive/refs/heads/master.tar.gz curl build-base octave-dev texinfo openblas-dev`.

Takes awhile to compile all the dependencies but those are cached after the first time so it needs a layer that runs octave to pre-cache them.
