### ISSUE TITLE
automate running containers on self hosted runner if necessary

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#138]
currently esilpd is too large to run on github and the workflow is hacked manually

https://github.com/NeuroDesk/neurocontainers/blob/master/.github/workflows/esilpd.yml

**Comment by stebo85** [comment]
- runs-on: needs to be set to self hosted
- Python setup needs to be disabled on self hosted runner

could be done via a text file similar to free-up space?

**Comment by stebo85** [comment]
this is what I tried, but not working yet: 

```
decide-where-to-run:
    runs-on: ubuntu-latest
    outputs:
      BUILDDATE: ${{ steps.ENVVARS.outputs.BUILDDATE }}
      RUNNERTYPE: ${{ steps.RUNVARS.outputs.RUNNERTYPE }}
    steps: 
      - uses: actions/checkout@v2
      - name: Set environment variables
        id: ENVVARS
        run: |
          echo `git --version`
          APPLICATION=$(basename $GITHUB_WORKFLOW .yml)
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
          BUILDDATE=`date +%Y%m%d`
          echo "APPLICATION=$APPLICATION" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
          echo "::set-output name=BUILDDATE::$BUILDDATE"
      - name: Check self-hosted list
        id: RUNVARS
        run: |
          SELFHOSTEDLIST=$(cat .github/workflows/free-up-space-list.txt)
          if [[ $SELFHOSTEDLIST == *"|$APPLICATION|"* ]]; then
            rm -rf $GITHUB_WORKSPACE/*
            RUNNERTYPE=self-hosted
          else
            RUNNERTYPE=ubuntu-latest
          fi
          echo "RUNNERTYPE=$RUNNERTYPE" >> $GITHUB_ENV
  build-docker:
    runs-on: self-hosted
    outputs:
      BUILDDATE: ${{ steps.ENVVARS.outputs.BUILDDATE }}
```

**Comment by aktech** [comment]
*Disclaimer: This doesn't answers the actual question, but suggests an alternative:*

Hey @stebo85 you can achieve this easily with https://cirun.io/ It creates on demand runners for GitHub Actions on your cloud and manages the complete lifecycle. You simply connect your cloud provider and define what runners you need in a simple yaml file and that's it.

See https://docs.cirun.io/reference/examples.html#aws for example.

**Comment by stebo85** [comment]
That's really cool! Thank you @aktech - that could indeed make our live a bit easier.

**Comment by aktech** [comment]
Thanks, let me know if you need any help. I am more than happy to help.

**Comment by stebo85** [comment]
@aktech - first problem: cirun doesn't support Oracle Cloud, which is the cloud provider we use and love. I send you a support message inside cirun.

**Comment by aktech** [comment]
> @aktech - first problem: cirun doesn't support Oracle Cloud, which is the cloud provider we use and love. I send you a support message inside cirun.

@stebo85 It does now 🚀 Here is an example repository: [AktechLabs/github-actions-on-oracle-cloud-example](https://github.com/AktechLabs/github-actions-on-oracle-cloud-example)

**Comment by stebo85** [comment]
working thanks to cirun
