### ISSUE TITLE
Use github actions reusable workflows

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurocontainers#141]
https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by stebo85** [comment]
That would avoid our many yaml files in neurocontainers? That would be cool:)

**Comment by aswinnarayanan** [comment]
Yes this should do the job. This functionality wasn't available initially when setting up the CI/CD. Will make things much cleaner

**Comment by aswinnarayanan** [comment]
Got this working on the test fork.
I'll consolidate some of the other container build fixes (depracations, os updates etc) and merge them as one update

**Comment by stebo85** [comment]
That's awesome :)

**Comment by aswinnarayanan** [comment]
To-do
- [ ] Re-add support for cirun

**Comment by aswinnarayanan** [comment]
Done
