### ISSUE TITLE
mne-lab

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#157]

**Comment by DavidjWhite33** [comment]
Hi @stebo85, there was a plan to have mne-lab running in the MNE extended container (indeed it is still part of the install yaml), but it has pyside6 as a dependency - while a number of the others use pyqt et al, and I was concerned about conflicts. Let me know if you suggestions on a path forward.

**Comment by stebo85** [comment]
Dear @DavidjWhite33,

You are the expert on these tools so I leave this decision to you. If you can include MNE-lab inside the MNE extended container that's wonderful. If not, and you think MNE-lab is useful, then maybe it's worth building it inside a separate container?

Thank you
Steffen

**Comment by DavidjWhite33** [comment]
Thanks @stebo85, I have not used mne-lab personally, but seems to make MNE python more accessible so probably worth trying to add it one way or another for those more comfortable with GUI. I am away for a couple of weeks, but will re-visit on my return.
