### ISSUE TITLE
Add micapipe!

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurocontainers#160]
Because it looks awesome
https://micapipe.readthedocs.io/en/latest/ 
Will work on this now

**Comment by stebo85** [comment]
I started with micapipe here: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/micapipe/build.sh

**Comment by stebo85** [comment]
related to https://github.com/NeuroDesk/neurocontainers/issues/604

**Comment by stebo85** [comment]
done
