### ISSUE TITLE
Matlab keyboard shortcuts

### ISSUE THREAD

**Issue by korbinian90** [NeuroDesk/neurocontainers#178]
The matlab GUI starts by default with emacs keyboard shortcuts (alt+w for copy, etc.)
matlab 2022a container

**Comment by felenitaribeiro** [comment]
This problem might relate to the wrapper script, which doesn't allow for parsing any argument at the moment.

**Comment by stebo85** [comment]
documented how to change keyboard layout: https://www.neurodesk.org/tutorials/programming/matlab/#changing-matlab-keyboard-shortcuts
