### ISSUE TITLE
Automatic tagging on any changes to the template app

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#193]
@stebo85 @aswinnarayanan 
I wonder -- is it possible to configure Github so every time certain files are changed, all the developers will be tagged?
If that's possible, can you refer me to an explanation on how to do it? Since we all use the template app to create new containers, I would like to configure Github to notify everybody on any changes there.

**Comment by stebo85** [comment]
We could lock the master branch - then every change has to go via a pull request, which would notify people. @aswinnarayanan what do you think?

**Comment by civier** [comment]
Other than Neurocontainers, is there any other repository in the Neurodesk
organisation that can be modified directly rather than via a pull request?

**Comment by stebo85** [comment]
no - we locked all other repositories down as well to avoid breaking things that people rely on - I think it would make sense to do the same for neurocontainers

**Comment by aswinnarayanan** [comment]
Yeah locking down master makes sense, we'd need to update the documentation correct?

**Comment by stebo85** [comment]
not much - I think we documented everything as pull requests already - assuming that contributors come from outside

**Comment by stebo85** [comment]
completed now: Neurocontainers repo now only works via pull requests. I removed the option in the documentation to clone repo and directly commit to master, because not everyone is familiar enough with git to avoid merge conflicts that then trigger other builds.
