### ISSUE TITLE
`git annex` opens a text editor instead of a browser

### ISSUE THREAD

**Issue by gllmflndn** [NeuroDesk/neurocontainers#210]
In Neurodesktop, clicking on `Internet` > `Git Annex` opens HTML content in `gedit` instead of displaying it in a browser.

**Comment by stebo85** [comment]
thank you so much for finding this :D I would have never clicked on this!

@aswinnarayanan - can we just remove the git annex thing from the menu :? Or should we try to fix it so it opens the browser?

**Comment by aswinnarayanan** [comment]
I can see how to fix the webapp. It should open in the browser

**Comment by aswinnarayanan** [comment]
Fixed in the latest nightly. So next release should resolve this issue
