### ISSUE TITLE
Automatic and semi-automatic testing of containers

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#221]
Dear all,

After some fieldwork, consultation and testing, I would like to suggest a framework for container testing.
I propose that each container will optionally include the 3 bash scripts below. I'm writing a central testing script to be executed inside Neurodesktop which will try to run these scripts for each container. Based on the output, it will generate a report. The idea is that the report will be reviewed each time we roll out a new Neurodesktop version. The report will indicate which packages passed the tests, which packages didn't pass them, and which packages do not include tests. Also, for tests that can not be fully automated, the report will include the output of the manual tests.

1. /neurodesk/return_auto_test_result.sh - for tests that can be fully automated
- should return 0 exit code if the container passed the test
- should return a non-zero exit code if the container failed the test, and an error message (if available) should be printed to stderr
- should return 1 exit code and print "N/A" to stderr if the container developer hasn't included this functionality yet (that will be the default if the script provided in the template has not been modified)
- any other stderr or stdout will be captured by my main testing script

2. /neurodesk/print_version.sh - for verifying that the version of the package is correct
- should return exit code 0 and print the version of the package (in exactly the same format used in Neurodesk) to stdout
- should return 1 exit code and print "N/A" to stderr if the container developer hasn't included this functionality yet (that will be the default if the script provided in the template has not been modified)
- should return non-zero exit code if the version cannot be retrieved, and an error message (if available) should be printed to stderr

3. /neurodesk/save_manual_test_to_folder.sh - for tests that cannot be fully automated
- should accept one argument with a folder name
- should return 0 exist code and save to the folder pairs of images, webpages or text files named 1-desired.ext and 1-generated.ext, 2-desired.ext and 2-generated.ext, etc.; these will be visually compared by the tester to verify a match. Extension (ext) should be .txt, .html, or any supported image format. If saving html, can also include subfolders.
- should return 1 exit code and print "N/A" to stderr if the container developer hasn't included this functionality yet (that will be the default if the script provided in the template has not been modified)
- should return non-zero exit code if there is a problem in running the test, and an error message (if available) should be printed to stderr

Let me know if you have any comments or suggestions,
Oren

**Comment by stebo85** [comment]
Dear @civier ,

I think this is a good idea. Feel free to go ahead with this, implement it, and test it out.

If it works well we can document it and add it to the template folder.

Kind regards
Steffen

**Comment by stebo85** [comment]
completed
