### ISSUE TITLE
containers don't build 

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#237]
I get this error when I try to manually trigger a build:

```
Run DOCKERFILE=`basename $(find .recipes/$APPLICATION/ -type f -iname "*.Dockerfile" | head -1)`
find: ‘.recipes/afni/’: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
Error: Process completed with exit code 1.

```
It seems that this also comes up when there is no change to a build script. Is this a new bug :?

**Comment by stebo85** [comment]
@aswinnarayanan 

I had to change this line:
```
DOCKERFILE=`basename $(find .recipes/$APPLICATION/ -type f -iname "*.Dockerfile" | head -1)`
```
to this to get it to work, but I don't understand why the location of the executing script changed. If you have any idea what I am missing let me know. I will keep this open until I understand the problem.
```
DOCKERFILE=`basename $(find . -type f -iname "*.Dockerfile" | head -1)`
```

**Comment by aswinnarayanan** [comment]
Oh there's a typo in my change
`.recipes` was supposed to be `./recipes`

**Comment by stebo85** [comment]
ok, that makes sense - I change it back then
