### ISSUE TITLE
VSCode  failed to open on CVL

### ISSUE THREAD

**Issue by yexincheng** [NeuroDesk/neurocontainers#245]
I tried to launch VSCode on CVL@Wiener FastX through the menu bar. I clicked vscodeGUI 220114, but the terminal closed in a second

**Comment by aswinnarayanan** [comment]
Thanks for reporting this @yexincheng, We need to fix the vscode container. Will update here when its done

**Comment by stebo85** [comment]
Problem is:

- for centos 7 it only works for no-sandbox -> try switching to ubuntu

**Comment by stebo85** [comment]
I made progress on this and got it to work:
1) VScode needs /run bind mounted, so everyone who wants to use it needs to export this in their .bashrc:

```
export SINGULARITY_BINDPATH=/afm02,/afm01,/run                                  
```

2) I added the --no-sandbox command line option 

A new container is currently building

**Comment by stebo85** [comment]
Dear @aswinnarayanan - can you update the containers on CVL? I added the new code container and it should work now :)

**Comment by stebo85** [comment]
ok, tested and working.
