### ISSUE TITLE
AFNI Region-based analysis is missing a required R package

### ISSUE THREAD

**Issue by araikes** [NeuroDesk/neurocontainers#247]
Hi all,

I am attempting to use AFNI's RBA in an analysis. The computational process works and generates outputs but there should be plots that accompany the outputs and it is failing there. This is because the R package `data.table` is not installed. Is there any way to add that package to the AFNI container?

**Comment by stebo85** [comment]
Yes, I can add this :) 

Can you send me command line to reproduce the problem so I can test?

**Comment by araikes** [comment]
You'll need a test file to run, which I've attached. Note that I pulled the container for our HPC rather than running in "NeuroDesk" specifically (`singularity pull docker://vnmd/afni_23.0.04`

`singularity exec /groups/adamraikes/singularity_images/afni-23.0.04_vnmd.sif RBA -prefix /path/to/output/prefix -chains 4 -iterations 1000 -ROI ROI -Y volume -model '1+group+treatment+tbv.c' -EOI 'treatment' -cVars -'group,treatment' -dataTable /path/to/volumes_v2.txt -ridgePlot 10 8`

It finishes without any error when not including `ridgePlot`

[volumes_v2.txt](https://github.com/NeuroDesk/neurocontainers/files/10829140/volumes_v2.txt)

**Comment by stebo85** [comment]
Dear @araikes 

We found a fix for your problem and there is now a new AFNI with version 23.0.07 which should work.

Can you test this?

Instead of pulling from docker and then converting to singularity you can also directly pull the singularity image as described here
https://www.neurodesk.org/docs/neurocontainers/singularity/

one example mirror would be:
```
curl -X GET https://objectstorage.us-ashburn-1.oraclecloud.com/n/sd63xuke79z3/b/neurodesk/o/afni_23.0.07_20230302.simg -O
```

**Comment by stebo85** [comment]
Dear @araikes 

Did you have a chance to test?

Thank you
Steffen

**Comment by araikes** [comment]
Sorry @stebo85, was out of town the end of last week. I'll test tomorrow.

**Comment by araikes** [comment]
Hi @stebo85,

That worked. Thanks.

**Comment by stebo85** [comment]
thank you for testing and confirming the fix :)
