### ISSUE TITLE
add a container with a collection of dicomtools

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#266]

**Comment by stebo85** [comment]
- dcm2niix
- dcmtk (sudo apt install dcmtk)
- dicomviewer (e.g. xmedcon: https://xmedcon.sourceforge.io/Main/Download)

**Comment by stebo85** [comment]
@thomshaw92 - would it make sense to have such a container?

**Comment by stebo85** [comment]
add pigz as well, see #333

**Comment by thomshaw92** [comment]
I think we already have this container, no?

**Comment by stebo85** [comment]
no, it doesn't exist yet - do you want to build it?

**Comment by thomshaw92** [comment]
I can do it next week :)

**Comment by stebo85** [comment]
this container exists as https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/bidstools/build.sh
