### ISSUE TITLE
I'm waiting 1 hour for a runner

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#275]
https://github.com/NeuroDesk/neurocontainers/actions/runs/4570666289/jobs/8068234844
Just wonder if it's normal or related to the bug in cirun you mentioned before?
In the future, how long should I wait before letting you know of issues with runners being scheduled?

**Comment by stebo85** [comment]
Yes, this is the bug again. The runner should start within 5 minutes.

**Comment by stebo85** [comment]
It's now all done.
