### ISSUE TITLE
Add pigz to all containers containing dcm2niix as default

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurocontainers#333]
Can you see any issue with doing this @stebo85 ?

```
$ sudo apt install pigz  [On Debian/Ubuntu]
$ sudo dnf install pigz  [On CentOS/RHEL/Fedora]
$ sudo pacman -S pigz    [On Arch/Manjaro Linux] 
OR
$ yay -S pigz
```

**Comment by stebo85** [comment]
yes, that's possible. Which containers contain dcm2niix?

**Comment by thomshaw92** [comment]
bidscoin/3.7.0
bidstools/1.0.0
I guess mricron also uses dcm2niix?
Should also make a dcm2niix container! Can't believe we are missing this one!
QSMxT?
MRTrix?
Nipype?
