### ISSUE TITLE
update aslprep

### ISSUE THREAD

**Issue by PatricioSolis-Urra** [NeuroDesk/neurocontainers#405]
Hi,  
I'm checking that there is a new version of aslprep (0.4.0)
Is possible to include this in neurodesk? 
Thanks a lot!
best,
Patricio

**Comment by stebo85** [comment]
Dear @PatricioSolis-Urra,

yes, we can update this :) I just did that and once build and tested it will be there.

Thank you
Steffen

**Comment by stebo85** [comment]
Dear @PatricioSolis-Urra ,

The new version for ASLprep is there. Can you test if it's all working as expected for you?

Depending on how you use Neurodesk you might have to click on the update button in the menu before the new entry gets added to the Application menu.

Kind Regards
Steffen

**Comment by PatricioSolis-Urra** [comment]
Thanks @stebo85 , it works.
best,
Patricio

**Comment by stebo85** [comment]
Thank you for testing :) would you be keen to contribute an aslprep tutorial or example notebook using open data (https://www.neurodesk.org/tutorials-examples/) so that we can test if it works and neurodesk users can see how to use it?

**Comment by PatricioSolis-Urra** [comment]
Hi @stebo85,
Sounds great! I would love to contribute to this. I'll take some time to review everything and then begin working on the example over the next few weeks.
best,
Patricio
