### ISSUE TITLE
use docker scan to look for vulnerabilities inside images during build on github actions

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#41]
https://docs.docker.com/engine/scan/

**Comment by stebo85** [comment]
There are several vulnerability scanning tools that you can easily incorporate into popular CI pipeline systems, including commercial solutions and open-source tools like Trivy or Anchore. Some scanners can also check for other security issues, like the presence of malware in an image.

**Comment by aswinnarayanan** [comment]
Scanning neurodesktop base container has been enabled in https://github.com/NeuroDesk/neurodesktop/commit/1033b321c31713ab9b3610736f4aeee730ad4eea

Shelving the neurocontainer scanning for now as it is currently un-tenable, the neurocontainers have a wider variety of older ubuntu/centos base images that can't be updated. Security model is moving towards locking down the neurocontainers, and keeping the neurodesktop image updated and secure.

**Comment by stebo85** [comment]
great :) thank you!
