### ISSUE TITLE
add brainnetviewer

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#46]
low priority @isabellabreukelaar

**Comment by stebo85** [comment]
MRIcro GL is available now @IsabellaBreukelaar -brainnetviewer comes next :)

**Comment by stebo85** [comment]
brainnetviewer: https://www.nitrc.org/projects/bnv/

**Comment by IsabellaBreukelaar** [comment]
Amazing! Thank you Steffen and team :)

**Comment by stebo85** [comment]
done.
