### ISSUE TITLE
should we rename caid to NeuroContainers

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#48]
caid was the original name of this repo when I started building containers, but since then it has evolved quite a bit and is now the central point for building and providing containers for neurodesk. I think this repo is very worthwile on it's own, so should we rename it to NeuroContainers to make this clearer?

**Comment by aswinnarayanan** [comment]
Sounds good. Should we do "neurocontainers"?

**Comment by stebo85** [comment]
ok, renamed :) It shouldn't cause any issues - but I guess we will find out if it does :D
