### ISSUE TITLE
CONN toolbox Update

### ISSUE THREAD

**Issue by AndreaCoca-Pulido** [NeuroDesk/neurocontainers#500]
Hi,
I'm checking that there is a new version of CONN toolbox (22.a)
Is it possible to include this in neurodesk?
Thanks a lot!
best,
Andrea

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido,

The 22.a version of the conn toolbox was unfortunately not released yet as a standalone version by the conn toolbox developers. The latest version available as a standalone is 21a:

https://www.nitrc.org/frs/?group_id=279

To integrate nicely on Neurodesk we require the standalone version that doesn't require a matlab license: These are indicated with _glnxa64, such conn21a_glnxa64.

There are a few paths forward:
- we can add version 21a if this is helpful to you
- you can contact the conn toolbox developers and ask if they could release a standalone version of 22a
- you could download the 22a version yourself and run it using Matlab and using your own Matlab license

What would work best for you?

Kind regards
Steffen

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido,

I created a forum post here to ask for a release of the standalone version: https://www.nitrc.org/forum/forum.php?thread_id=14696&forum_id=1144

Kind regards
Steffen

**Comment by stebo85** [comment]
I tried building 21a, but the standalone version doesn't work:

conn-21a:~$ conn
Initializing MATLAB Runtime version 9.10
Loading MCR. Please wait...
Warning: Removing "/home/jovyan/.mcrCache9.10/conn_d0/project/busplab/software/spm12/external/fieldtrip/compat/matlablt2016b" from your path.
See http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/
Error using fullfile (line 103)
All inputs must be strings, character vectors, or cell arrays of character vectors.

Error in runtimeInitializationChecks (line 12)

MATLAB:fullfile:InvalidInputType

**Comment by AndreaCoca-Pulido** [comment]
Hi Steffen,

Thank you so much for your interest and concern in helping me with this. It
looks like I would have to wait until they release the standalone or answer
the forum. Hopefully It will be soon.

Thank you very much again,

Kind regards,

Andrea


Andrea

*Andrea Coca Pulido*
University of Granada
Biomedicine PhD Student
Department of Physical Education and Sports
Granada, Spain.
Research Group: http://profith.ugr.es/
Twitter: @acocapulido <https://twitter.com/acocapulido?lang=es>

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido,

There has unfortunately not been a reply on the forum - can you contact the authors of the conn toolbox as well and ask for a compiled version?

Alternatively, you can run conn toolbox in Matlab using your institutional license.

Kind regards
Steffen

**Comment by AndreaCoca-Pulido** [comment]
Thank you very much, I will do that.
Andrea

*Andrea Coca Pulido*
University of Granada
Biomedicine PhD Student
Department of Physical Education and Sports
Granada, Spain.
Research Group: http://profith.ugr.es/
Twitter: @acocapulido <https://twitter.com/acocapulido?lang=es>

**Comment by AndreaCoca-Pulido** [comment]
Dear Steffen Bollmann,

This is the response  I got from the authors of the conn toolbox:

*"Hi Andrea*

*I have now uploaded to NITRC CONN's version 2022a compiled for linux
machines. The installation files/instructions are available at *

*https://web.conn-toolbox.org/resources/installation/standalone-linux*
<https://web.conn-toolbox.org/resources/installation/standalone-linux>

*Tthe CONN 2022a installation files are now available at:*

*https://www.nitrc.org/frs/download.php/13733/conn22a_glnxa64.zip*
<https://www.nitrc.org/frs/download.php/13733/conn22a_glnxa64.zip>

*and the corresponding version of MCR is now MCR 2022a (9.12), which can
also be downloaded from: *

*https://www.nitrc.org/frs/downloadlink.php/13734*
<https://www.nitrc.org/frs/downloadlink.php/13734>

*Let me know if you need any additional information and/or if you run into
any issues*

*Best*
*Alfonso"*

Does this solve the problem you had with the installation?

Thank you very much for everything,


Andrea

*Andrea Coca Pulido*
University of Granada
Biomedicine PhD Student
Department of Physical Education and Sports
Granada, Spain.
Research Group: http://profith.ugr.es/
Twitter: @acocapulido <https://twitter.com/acocapulido?lang=es>

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido ,

Great :) I now added this new version to Neurodesk. You need to click the "Update" button in the menu to make the new version visible in the menu system:

<img width="723" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/9d231b24-9315-41b3-9c1f-6516e544d569">

Let me know if everything works as expected!

Thank you
Steffen

**Comment by AndreaCoca-Pulido** [comment]
Dear @stebo85,

It seems that something is not working well in the new installation of the conn22a. I have detected several issues:

1. When I update neurodesk in this Mac (characteristics in the photo), neither the conn22a nor the connGUI22a do not appear so that i can not run it. 
![Captura de pantalla 2023-11-27 a las 10 52 53](https://github.com/NeuroDesk/neurocontainers/assets/93335172/b5b39e76-3dd9-4dea-8493-f651a1346589)

2. When I update neurodesk in this Macbook (characteristics in the photo), the conn22a and the connGUI22a appear but when i click on them, it seems that just the conn22a works but not the GUI (the one that i need) and i try to open it through bash using ml conn/22a and it replies me with this error:

conn-22a:~$ ml conn/22a
bash: /usr/share/lmod/lmod/libexec/ml_cmd: No such file or directory

<img width="262" alt="Captura de pantalla 2023-11-27 a las 10 55 10" src="https://github.com/NeuroDesk/neurocontainers/assets/93335172/10ad4c8f-d215-40d8-87b1-4417349ad88a">

So i dont really know what it is happening. If you could help me to solve this problem it would be very helpful.

Thank you so much,
Andrea

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido ,

We just released a new version of Neurodesk (Neurodeskapp 1.3.0, Docker image version vnmd/neurodesktop:2023-11-28) which should fix your problem on both Mac systems you have. Can you test and confirm?

Thank you
Steffen

**Comment by AndreaCoca-Pulido** [comment]
Dear @stebo85,

It does not appear in the Mac Pro, however It appears already in my Macbook Pro but it works a little slow...

I dont really know what it is happening with the Mac...

Thank you so much!

Andrea

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido ,

1) can you check which version of neurodesk you are running?
2) can you check if you enabled Rosetta in your docker settings?

thank you
Steffen

**Comment by AndreaCoca-Pulido** [comment]
Dear @stebo85 

1. I am trying to find where to see this info.
2. I think i did not enable it because i found this message:
![Captura de pantalla 2023-12-08 a las 11 43 41](https://github.com/NeuroDesk/neurocontainers/assets/93335172/8e4101a2-bd99-422b-813c-432e656c8c72)

But I dont know why it is working so slow knoe,

I´ll answer to 1. whenever the PC´ll let me,

Thank you so much,

Andrea

**Comment by stebo85** [comment]
1.  you can see the neurodesk app version by clicking on about - it needs to be 1.3.0
2) you need Rosetta enabled in docker - otherwise it’s 80% slower. So update and then enable it.


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________

**Comment by AndreaCoca-Pulido** [comment]
My neurodesk app version is 1.3.0 so it is fine. 
I think rosetta is know enabled: 
<img width="814" alt="Captura de pantalla 2023-12-08 a las 12 03 32" src="https://github.com/NeuroDesk/neurocontainers/assets/93335172/75abb51a-fdfb-4c9e-b62e-e0162cbb10a6">

**Comment by AndreaCoca-Pulido** [comment]
I could not check it in the Mac PRO because we are having some internal issues. However, Although i did what you told me to do to make it work faster, it still goes so slow, dont know why

**Comment by stebo85** [comment]
Can you copy the data to your homedirectory inside neurodesk and try again? Can you also describe what exactly you are doing and what exactly is slow?

**Comment by stebo85** [comment]
Dear @AndreaCoca-Pulido,

Can you confirm that everything is working for you now, so I can close this issue?

Thank you
Steffen

**Comment by AndreaCoca-Pulido** [comment]
oh sorry, I totally forgot that everything was working great! Thank you so much! You have been so helpful😀

**Comment by stebo85** [comment]
Wonderful- thank you for confirming:) what solved the speed issues you were seeing?

**Comment by AndreaCoca-Pulido** [comment]
I guess freeing up memory space helped a bit hahahaah We are running many analyses and generating many heavy documents....

**Comment by stebo85** [comment]
Ok, that makes sense! Thank you for reporting back and glad to hear it’s working now as expected:)
