### ISSUE TITLE
Unnecessary files in aslprep_0.2.7_20210323 

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#53]
aslprep_0.2.7_20210323 has many files in /tmp (source and build of ants), which unnecessary contribute to the size and number of files in the container.

**Comment by stebo85** [comment]
We do not build aslprep ourselfs, but pull it directly from the developer: https://hub.docker.com/r/pennlinc/aslprep/tags?page=1&ordering=last_updated

Please flag this directly with the container developer

**Comment by civier** [comment]
Cool. I didn't know it's possible that easily.
Can we include in NeuroDesk any containers whatsoever, or does it need to
comply with some requirements?
What happens if the container is using one of the paths where we bind
things?
How do you know where the executables within the container are? (just
exploring the container?)

Best,
Oren

**Comment by stebo85** [comment]
Dear @civier ,

Yes, in principle we can use any container as a base. We then add customizations around it in the buildscripts. See the aslprep example here: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/aslprep/build.sh

if a container would use a directory where we bind directories, these directories will be overritten.

The binary paths are defined via the DEPLOY_BINS variable
```
--env DEPLOY_BINS=aslprep \
```
