### ISSUE TITLE
Adding QSIprep

### ISSUE THREAD

**Issue by johnaeanderson** [NeuroDesk/neurocontainers#531]
I am loving the neurodesktop setup, but I would really appreciate having the QSIprep (https://qsiprep.readthedocs.io/en/latest/index.html) workflow for diffusion-weighted-imaging available.

**Comment by stebo85** [comment]
Dear John, this would be great :) it would be very similar to the fmriprep recipe: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/fmriprep/build.sh

would you like to send the recipe via a pull request to the neurocontainers repository?

**Comment by stebo85** [comment]
Dear @johnaeanderson - just wondering if you are still interested in this and if you are working on a pull request? Do you need help with this? If you can't do it yourself, would you like me to do it?

Thank you
Steffen

**Comment by stebo85** [comment]
I am starting to work on this now

**Comment by stebo85** [comment]
container is ready for testing: 
```
bash /neurocommand/local/fetch_and_run.sh qsiprep 0.20.0 20240408
```

once tested I will release.

**Comment by stebo85** [comment]
Dear @johnaeanderson,

qsiprep 0.20.0 is now released on Neurodesk. You can use it either via the module system:
<img width="1075" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/b54620fb-7df4-4864-b1cc-a2e523e98f3c">

or through the application menu after clicking "Update" in the menu:
<img width="710" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/6aa5f745-4daf-42d7-b6d3-8133e8695062">

Please report back if it works well :)

Thank you
Steffe
