### ISSUE TITLE
Using MATLAB Compiler to create standalone packages

### ISSUE THREAD

**Issue by DavidjWhite33** [NeuroDesk/neurocontainers#55]
Hi @stebo85, wondering if you already documented a workflow for compiling MATLAB packages not already compiled (eg. when building CONN)? If so, could you please share?

Ie. did you use the MATLAB compiler for your CONN archive, or is this a compiled version accessed by the developers (https://objectstorage.us-ashburn-1.oraclecloud.com/n/nrrir2sdpmdp/b/neurodesk/o/conn20b_mcr2020b.tar.gz)

Also, should we organise the central/open place for storage of these archives?

@civier

**Comment by stebo85** [comment]
@civier and @DavidjWhite33 - I trasnferred the issue to the neurocontainers repo

**Comment by DavidjWhite33** [comment]
> I think we should use compiled MATLAB packages if they are available by the developers of the toolbox and they work (like SPM). If they are not available, we have to try and compile them ourselves. Once compiled we should upload them to our container object storage - I can send you a pre-authenticated curl command that can do this - let me know if you want this and I send it to you.
> 
> Which toolbox are you compiling right now?
> 
> Cheers
> Steffen

@stebo85 Agreed that using compiled versions released by developers makes sense wherever possible. I am looking at a couple of toolboxes at the moment - but one important one is EEGLAB. This is an interesting case because they have a standalone compiled version to run with MCR, but have stopped releasing this for linux as of their first 2020 release. In addition, there is perhaps an argument for the added flexibility of compiling ourselves to incorporate additional add-on tools that aren't compiled with the main standalone version. As a final wrinkle, EEGLAB developers have stated they will now support an Octave release for HPC etc - as this sounds like a less stable solution at this point, this may be something to just keep an eye on.

**Comment by stebo85** [comment]
Fully agree! Octave is an interesting option and SPM runs very well in Octave as well. This is something we should explore if we can find the time for this.

I also just figured out a sneaky way of compiling matlab code on github automatically :D we could use the official matlab container (https://hub.docker.com/r/mathworks/matlab) and inject our university license in there in case we have the cloud option licensed (https://hub.docker.com/r/mathworks/matlab)

I would probably set this up in a separate new repository - @civier or @DavidjWhite33 would you like to look into this?

Kind regards
Steffen

**Comment by civier** [comment]
Thanks for the valuable information, @stebo85 <https://github.com/stebo85>
I'm trying to read through here:
https://au.mathworks.com/help/licensingoncloud/ug/configure-license-for-mathworks-containers.html
But will have to play with it a bit.

BTW, did you manage to run the Matlab IDE (not the container) with your UQ
site license on NECTAR? Until now, I've just used an individual license
(that each staff member is provided with by Swinburne) and it worked fine.

Best,
Oren

**Comment by stebo85** [comment]
Ok, great :) looking forward to see your progress on this.


I haven't used Matlab for a few years, so no I haven't tried running it on nectar :)

**Comment by stebo85** [comment]
closing for now, as compiling of matlab toolboxes works right now
