### ISSUE TITLE
Matlab containers

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#56]
It looks like it is possible to package matlab in our singularity containers. We only would need to document how users can inject their license (e.g. by placing a license file in the /neurodesktop-storage folder?

Anyone interested to work on this issue?
https://au.mathworks.com/help/cloudcenter/ug/matlab-container-on-docker-hub.html#:~:text=MATLAB%20Container%20on%20Docker%20Hub%20Access%20MATLAB%20%C2%AE,information%20on%20containers%2C%20see%20What%20is%20a%20Container%3F.

**Comment by stebo85** [comment]
@civier is anyone looking into getting Matlab containers working? If not I could have a look at this next week.

**Comment by civier** [comment]
Hello Steffen,

This is my plan:
1) make it easy for users to add into NeuroDesk a container with an already-compiled Matlab software (e.g., CONN)
2) Let users use Matlab IDE in NeuroDesk using individual or site license
3) have instructions on how users can compile their own MATLAB pipeline (and make a container out of it) so other NeuroDesk users can use it without license

I'm not sure if the Matlab container has the full IDE, but if yes, I will look at it for number 2.
That said, you're of course welcome to check it yourself if you have time :-)

Thanks again for the info on the Matlab container,
Oren

**Comment by stebo85** [comment]
Dear @civier,

Ok, would be great to see this working!

Kind regards
Steffen

**Comment by civier** [comment]
Hi Steffen,

Dave and I are still working on adding NeuroDesk containers with compiled
MATLAB packages. It is the top priority for us.
Only when the procedure will be in place, I'll move to the MATLAB
container/IDE. If it is urgent, you're welcome to take a shot at that and
keep me in the loop.
(sorry again for the slowness, but as you probably know, we are still under
lockdown with kids at home. Hopefully things will get better in a couple of
weeks when they are back in school)

Best,
Oren

**Comment by stebo85** [comment]
Ok, sounds good. Happy to help if you are stuck at anything.

**Comment by stebo85** [comment]
Matlab now has a feature to package compiled applications direclty into a docker container: https://www.mathworks.com/help/compiler/package-matlab-standalone-applications-into-docker-images.html

@DavidjWhite33

**Comment by stebo85** [comment]
done - please feel free to reopen if anything is missing

**Comment by thomshaw92** [comment]
Bumping this - We want to get Matlab 2013 into a container - @korbinian90

**Comment by stebo85** [comment]
@thomshaw62,

https://hub.docker.com/r/mathworks/matlab/tags
R2020b is the oldest we can do as a full matlab install.

However, the matlab runtimes environments can be older. Can you compile your code?
