### ISSUE TITLE
Provide more elaborate instructions on adding software containers to neurocontainers

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#58]
Hello all,

I wrote more elaborated instructions on adding software containers, as it be a bit tricky to people who don't regularly work with github (especially with the new Personal Access Token and the fact that the workflow is updated as well).

@stebo85 @aswinnarayanan Can you approve?
@air2310 Nice to meet! Could you please update it in the documentation after Steffen/Aswin approve, and post here a link? I couldn't find the instructions to add containers on the new documentation pages.
@DavidjWhite33 @willw1 I hope this will be helpful for you when adding containers.

Best,
Oren

----

_newapp_ is the name of the new software container

**1. Sync neurodocker**
If the new container relies on changes that were made in neurodocker, request Steffen or Aswin to sync our fork of neurodocker with the current master at Repronim/neurodocker.
 
**2. Clone the repository**
git clone https://github.com/NeuroDesk/neurocontainers/

**3. Copy the directory template and rename to newapp in neurocontainers/recipes**
cd neurocontainers/recipes
cp -R template _newapp_

**4. Modify build.sh in neurocontainers/recipes/newapp to build your application and update README.md**
cd _newapp_
(edit build.sh as required)
(edit README.md as required)

**5. Run update-builders.sh. This will auto-create the CI workflow for the application (or duplicate the template file and rename all occurances of template to newapp)**
cd ../..
sh update-builders.sh

**6. update changes in local git**
git add recipes/_newapp_/build.sh recipes/newapp/README.md .github/workflows/_newapp_.yml
git config user.email "_the email that you use for github_"
git config user.name "_your name_"
git commit

**7. Generate git personal access token (if you don’t have one already)**
Browse to https://github.com/NeuroDesk/neurocontainers/
Press on your picture in upper right corner --> Setting --> Developer Settings --> Personal Access Token
Press on “generate personal access token”
Write something in “Notes” (doesn’t matter what, it’s for your own use)
Check “repo”
Check “Workflow”
Press “Generate Token” at the bottom
Copy the token displayed on the screen into a file, so you’ll have it later

**8. push changes to github**
git pull
git push
(enter you github username, and for password, copy and paste your personal access token)

**9. Check package is generated properly**
Go to neurocontainers/actions
Check that the most recent workflow run in the list terminated successfully (green)
Otherwise, click on it, click on “build docker”, and the line that caused the error will be highlighted

**10. Check that the package shows up in repository**
Go to https://github.com/orgs/NeuroDesk/packages?repo_name=neurocontainers and check that the new package is listed

**11. Try to manually download the package to your NeuroDocker or VNM**
bash /neurodesk/local/fetch_and_run.sh _newapp_ _newappversion_ _builddate_
ml _newapp_/_newappversion_

**12. Test the new container**
Run some commands, to see all is good

**Comment by stebo85** [comment]
Dear @civier ,

The container building was documented here: https://neurodesk.github.io/developers/new_tools/add_tool/

and I now added your additional steps in between.

I also added @civier @air2310 @DavidjWhite33 @willw1 as Admins to the neurodocker repository fork so you can pull in changes from upstream, create branches with new features and submit pull request to the upstream project.

Cheers
Steffen
