### ISSUE TITLE
Do not build / remove software collections

### ISSUE THREAD

**Issue by marcelzwiers** [NeuroDesk/neurocontainers#596]
BIDScoin is a separate neurocontainer, but it is also contained in `bidstools`:
```
## bidstools/1.0.2 ##
Contains a collection of tools useful for DICOM to BIDS conversion

Tools included:
dcm2niix: v1.0.20230411 https://github.com/rordenlab/dcm2niix
bidscoin: https://bidscoin.readthedocs.io
dcmtk: https://support.dcmtk.org/docs/pages.html
xmedcon: https://xmedcon.sourceforge.io/
heudiconv: https://heudiconv.readthedocs.io/en/latest/heuristics.html
Bru2Nii: https://github.com/neurolabusc/Bru2Nii
```
As far as I know, none of these tools depend on each other, and in my view neurodesk / the user is much better off loading the individual modules than loading a single module with the same collection of outdated (at least that will happen quickly) packages. Is it an option to remove these containers, or at least flag them as `NOT MAINTAINED` or so?

**Comment by marcelzwiers** [comment]
Instead of building a container for it, you could also just simply make a software collection module (that loads the individual modules)

**Comment by stebo85** [comment]
yes, that's a good idea. Will remove bidscoin from this container.

**Comment by marcelzwiers** [comment]
Ok, but it's not just bidscoin, also the other applications do not depend
on each other and are better off in their own container?

_____________________
Sent from my phone

Op di 20 feb 2024 23:06 schreef Steffen Bollmann ***@***.***>:

**Comment by stebo85** [comment]
yes, but isn't there also value in packaging tools with common tasks in one container? If every tool is in its own container then an HPC user has to download all of the individual containers for example. It would also clutter the Application menu if every little tool gets it's own entry. Also users don't often know what tools can be used for a certain task - so bundling tools with common tasks would help in discovery?

**Comment by stebo85** [comment]
Yes, bundling individual tools on the module level would be a great solution, but currently, our module generation scripts do not support this yet. We also want to move the application menu system to use the module system, but this is not yet completed: https://github.com/NeuroDesk/neurocommand/issues/152, this is also connected to the SHPC rewrite: https://github.com/NeuroDesk/transparent-singularity/issues/7 - we are currently trying to get resources to work on this, but until we have this completed, bundling tools in one container is our best option.

**Comment by marcelzwiers** [comment]
Ok, I see. Does this mean that you can only load one module at the same
time in neurodesk?

Op di 20 feb 2024 om 23:27 schreef Steffen Bollmann <
***@***.***>:

**Comment by stebo85** [comment]
No, you can already load multiple modules in Neurodesk at the same time. What's not yet possible right now is to create a meta-module that loads multiple other modules automatically. So to implement your suggestion, we would need a meta-module called "bidstools" that would then load individual containers like bru2nii, bidscoin, dcm2niix ... this then also needs to be integrated into the Application menu to avoid cluttering the menu with lot's of little tools. It's definitely something we want to do, but we currently lack the resources to implement this
