### ISSUE TITLE
Add latest version of micapipe v0.2.3

### ISSUE THREAD

**Issue by Yibh22** [NeuroDesk/neurocontainers#604]
Dear experts,

I came from this page: https://www.neurodesk.org/developers/new_tools/interactive_build/. And I want to add the latest version of micapipe to the neurodesktop on my local computer.

**Comment by stebo85** [comment]
Dear @Yibh22,

I added you to our interactive container builder :) It would be wonderful if you could contribute micapipe to Neurodesk.

Let us know if you need any help!

Thank you
Steffen

**Comment by stebo85** [comment]
superseded by https://github.com/NeuroDesk/neurocontainers/issues/772
