### ISSUE TITLE
New container topaz 0.2.5

### ISSUE THREAD

**Issue by vnm-neurodesk** [NeuroDesk/neurocontainers#613]
There is a new container by @stebo85, use this command to test:
```
bash /neurocommand/local/fetch_and_run.sh topaz 0.2.5 20240313
```

If test was successful, then add to apps.json to release:
https://github.com/NeuroDesk/neurocommand/edit/main/neurodesk/apps.json

Please close this issue when completed :)

**Comment by stebo85** [comment]
@vennand

**Comment by vennand** [comment]
@stebo85 

I couldn't figure how to test it in relion (since module load topaz from the relion test container didn't work), but there was no issue that I could find with this software.

I think this can go into release.
(can I add it to the app.json myself, or do you have to do it?)

**Comment by stebo85** [comment]
Great, you can add it to apps.json yourself and send a pull request
