### ISSUE TITLE
New container nighres 1.5.1

### ISSUE THREAD

**Issue by piloubazin** [NeuroDesk/neurocontainers#686]
Hello!
Here is a simple container for the nighres toolbox. I couldn't attach the build.sh so I made a link instead:
https://drive.google.com/file/d/1zhqMJ6oqkUHj42P3cr5ViBrdaYTzsSQH/view?usp=drive_link

[README.md](https://github.com/NeuroDesk/neurocontainers/files/15419461/README.md)

Thanks for this effort, hopefully it works out well!
Cheers,

Pilou Bazin

**Comment by stebo85** [comment]
@piloubazin - could you make the file publicly accessible? Or put it in a github gist?

**Comment by piloubazin** [comment]
I made the link open, I hope that works for you?

**Comment by stebo85** [comment]
Yes, I was able to access it

**Comment by stebo85** [comment]
completed :)

**Comment by piloubazin** [comment]
:partying_face: 
Thanks!
