### ISSUE TITLE
fetchcontainers doesn not update the run-scripts

### ISSUE THREAD

**Issue by marcelzwiers** [NeuroDesk/neurocontainers#702]
If you run `fetch_containers.sh` it nicely skips downloading a container image if it's already there. However, it then also skips reinstalling the transparent singularity scripts. But these two things are maintained/updated independently, and hence it may be desirable to reinstall the transparent singularity run-scripts, even if the container is already there?

**Comment by stebo85** [comment]
Dear Marcel,

I had a look at it and thought about how to implement that. The current behaviour is intended: if a container is installed we are not changing anything to keep reproducibility and to avoid breaking people’s workflows. If you want to trigger a regeneration of these scripts you need to delete the container. We can and should make this more explicit in the documentation. Can you suggest a documentation amendment?


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________
From: Marcel Zwiers ***@***.***>
Sent: Friday, May 31, 2024 10:39:51 AM
To: NeuroDesk/neurocontainers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NeuroDesk/neurocontainers] fetchcontainers doesn not update the run-scripts (Issue #702)


If you run fetch_containers.sh it nicely skips downloading a container image if it's already there. However, it then also skips reinstalling the transparent singularity scripts. But these two things are maintained/updated independently, and hence it may be desirable to reinstall the transparent singularity run-scripts, even if the container is already there?
