### ISSUE TITLE
New container mrtrix3src latest

### ISSUE THREAD

**Issue by vnm-neurodesk** [NeuroDesk/neurocontainers#721]
There is a new container by @stebo85, use this command to test:
```
bash /neurocommand/local/fetch_and_run.sh mrtrix3src latest 20240709
```

If test was successful, then add to apps.json to release:
https://github.com/NeuroDesk/neurocommand/edit/main/neurodesk/apps.json

Please close this issue when completed :)

**Comment by stebo85** [comment]
@timrosenow - can you test if this container works as expected?

**Comment by timrosenow** [comment]
Yes this works as expected, thank you so much!

**Comment by timrosenow** [comment]
Created pull request for apps.json
