### ISSUE TITLE
Cannot build bart container any more

### ISSUE THREAD

**Issue by dabosch** [NeuroDesk/neurocontainers#735]
Hi,

after just changing the base image, the build fails in a spot that looks completely unrelated to me:
https://github.com/NeuroDesk/neurocontainers/actions/runs/10054389818

Best,
Dario

**Comment by stebo85** [comment]
Yes, that is my fault - breaking the build when trying to fix the download link.

From: Dario Bosch ***@***.***>
Date: Tuesday, 23 July 2024 at 9:15 AM
To: NeuroDesk/neurocontainers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NeuroDesk/neurocontainers] Cannot build bart container any more (Issue #735)

Hi,

after just changing the base image, the build fails in a spot that looks completely unrelated to me:
https://github.com/NeuroDesk/neurocontainers/actions/runs/10054389818

Best,
Dario

**Comment by stebo85** [comment]
@dabosch, fixed now: https://github.com/NeuroDesk/neurocontainers/actions/runs/10054917546/job/27790456766

sorry for that - should have seen that earlier.
