### ISSUE TITLE
Updating AFNI dependencies

### ISSUE THREAD

**Issue by mrneont** [NeuroDesk/neurocontainers#791]
Howdy-

I recently checked in on the AFNI install on Neurodesk.  I think there are a couple of things to update there:

* We now use the Python modules Flask and Flask-Cors for setting up a local server to interact with afni_proc.py's QC HTML.  Those don't appear to be available after `ml afni`.
* We also use NiiVue as part of the same APQC HTML.  We distribute this with our binaries and as part of our build scripts, which basically means building+copying in a compiled `niivue_afni.umd.js` file in the same location as the main AFNI binaries (i.e., where `which afni` points).  We actually put a copy of the `niivue_afni.umd.js` file that we build in an openly accessible spot for ease of access, and so it could be gotten with:
    ```
     curl -O https://afni.nimh.nih.gov/pub/dist/bin/misc/niivue_afni.umd.js
    ```

It would be great if both of those aspects could be updated.

thanks,
pt

**Comment by stebo85** [comment]
This is now completed in our latest afni container with version 24.3.00
<img width="802" alt="image" src="https://github.com/user-attachments/assets/9cfb454e-273b-4948-8f9c-a3116d5a1c27">

Thank you for flagging this with us:)
