### ISSUE TITLE
New container niimath 1.0.0

### ISSUE THREAD

**Issue by vnm-neurodesk** [NeuroDesk/neurocontainers#796]
There is a new container by @stebo85, use this command to test on Neurodesk (either a local installation or https://play.neurodesk.org/):
```
bash /neurocommand/local/fetch_and_run.sh niimath 1.0.0 20240902
```
Or, for testing directly with Apptainer/Singularity:
```
curl -X GET https://neurocontainers.neurodesk.org/temporary-builds-new/niimath_1.0.0_20240902.simg -O
singularity shell niimath_1.0.0_20240902.simg
```

If test was successful, then add to apps.json to release:
https://github.com/NeuroDesk/neurocommand/edit/main/neurodesk/apps.json

Please close this issue when completed :)

**Comment by Vbitz** [comment]
Confirmed working locally.
