### ISSUE TITLE
New container brainnetviewer 1.7.20191031

### ISSUE THREAD

**Issue by vnm-neurodesk** [NeuroDesk/neurocontainers#798]
There is a new container by @Vbitz, use this command to test on Neurodesk (either a local installation or https://play.neurodesk.org/):
```
bash /neurocommand/local/fetch_and_run.sh brainnetviewer 1.7.20191031 20240904
```
Or, for testing directly with Apptainer/Singularity:
```
curl -X GET https://neurocontainers.neurodesk.org/temporary-builds-new/brainnetviewer_1.7.20191031_20240904.simg -O
singularity shell brainnetviewer_1.7.20191031_20240904.simg
```

If test was successful, then add to apps.json to release:
https://github.com/NeuroDesk/neurocommand/edit/main/neurodesk/apps.json

Please close this issue when completed :)

**Comment by Vbitz** [comment]
Confirmed working locally.

The failed build is due to Diva miscalculating the base image size.
