### ISSUE TITLE
Update AFNI

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurocontainers#811]
to 24.2.02 or later for new nonlinear warp commands.

**Comment by thomshaw92** [comment]
Noting that Neurodocker is currently failing at building AFNI from source 
"Building AFNI from source is currently failing on most tested distributions." 

So will hold off from this for now

**Comment by stebo85** [comment]
we are not building from source - so should be fine. Just update the recipe and it should build the new version

**Comment by stebo85** [comment]
completed. 24.3.00 is now available and working.
