### ISSUE TITLE
add more informative prompt in containers

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#84]
https://stackoverflow.com/questions/61116965/how-to-change-the-default-prompt-in-a-singularity-container

**Comment by stebo85** [comment]
@AKSoo suggested:
Changing the .desktop shortcut Exec to /bin/bash -c 'cat readme; $SHELL' accomplishes what I have in mind, but I am not sure how to implement this in the neurodesktop image

**Comment by aswinnarayanan** [comment]
We can do that via neuroommand. Pretty straight forward 
It would then deploy onto neurodesktop correct?

**Comment by AKSoo** [comment]
The suggestion was more for neurodesktop menu shortcuts. Bash `--rcfile` option may be also relevant. https://stackoverflow.com/questions/33961229/how-to-source-additional-file-when-launching-bash

**Comment by aswinnarayanan** [comment]
Thanks @AKSoo
neurocommand creates the menu entries. I'll push this change through shortly

**Comment by stebo85** [comment]
there are 3 issues here:

- [ ]  change name of prompt

- [ ] display readme when running GUIs

- [ ] create citeme file on desktop based on README.md  (https://github.com/NeuroDesk/neurodesk.github.io/issues/75)
