### ISSUE TITLE
new version of DSI Studio

### ISSUE THREAD

**Issue by karl-koschutnig** [NeuroDesk/neurocontainers#842]
I would like to provide a new version of dsistudio. Please find attached the build.sh and READMEN.md (as a zip file). 
[Archiv.zip](https://github.com/user-attachments/files/17278892/Archiv.zip)

**Comment by stebo85** [comment]
thank you. Building now.

**Comment by stebo85** [comment]
The current version doesn't work unfortunatley due to a QT error. I opened an issue: https://github.com/frankyeh/DSI-Studio/issues/92

**Comment by karl-koschutnig** [comment]
I had no problems in the interactive building mode in the Neurodesk environment. I tried it out and it worked?

**Comment by stebo85** [comment]
ok, good to know - I will have a look

**Comment by stebo85** [comment]
ok, problem found and updated dsi-studio version is now released. https://github.com/NeuroDesk/neurocommand/pull/321

Can you test on your side and confirm it's working as expected?

**Comment by karl-koschutnig** [comment]
Everything works as expected - thank you so much!!
