### ISSUE TITLE
Spinal Cord Toolbox fixes

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurocontainers#90]
Need to install Version 5.4 
I've noticed some of the templates that should be installed automatically with SCT are not available using the containers:
![image](https://user-images.githubusercontent.com/31721414/144971628-9f92e6a9-6665-4686-9c89-be17249f11b2.png)

I believe this is the SCT_DIR env missing

**Comment by stebo85** [comment]
Dear @thomshaw92 - sct is updated to 5.4 and this bug is fixed in the latest neurodesk version: 20211213

Can you test and report if this works?

Kind regards
Steffen

**Comment by stebo85** [comment]
Dear @thomshaw92 - did you have chance to test if SCT works now correctly? Then I can close this issue :)

**Comment by stebo85** [comment]
Dear @thomshaw92 did you have a chance of testing this? I also updated to the latest version of sct :)

**Comment by thomshaw92** [comment]
Sorry for the slow response. 5.4 was working at last test - will test 5.5 today :D

**Comment by stebo85** [comment]
@thomshaw92  tested and confirmed it's working
