### ISSUE TITLE
change prompt name in singularity containers from Singularity> to version of tool

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#95]

**Comment by stebo85** [comment]
discussed in #84

**Comment by stebo85** [comment]
started working on this: will add another configuration file in singularity on cvmfs:

    # echo "check if custom promt exists for singularity:"
    # if [[ -f "/cvmfs/neurodesk.ardc.edu.au/containers/${IMAGENAME_BUILDDATE}/${IMAGENAME_BUILDDATE}.simg/.singularity.d/env/99-zz_custom_env.sh" ]]
    # then
    #     echo "99-zz_custom_env exists for ${IMAGENAME_BUILDDATE} on cvmfs"
    # else
    #     echo "99-zz_custom_env does not exist for ${IMAGENAME_BUILDDATE} on cvmfs. Creating it."
    #     CUSTOM_ENV=/.singularity.d/env/99-zz_custom_env.sh
    #     echo "#!/bin/bash" >> $CUSTOM_ENV
    #     PS1="[my_container]\w \$"
    #     EOF
    #         chmod 755 $CUSTOM_ENV
    # fi

in sync_containers_to_cvmfs.sh

Idea is to not break a "standard" singularity container (therefore not during build), but on cvmfs we can do what we like after the container was unpacked. This will also allow us to revert this quickly in case of adverse effects. Or modications required later.

**Comment by aswinnarayanan** [comment]
Added in https://github.com/NeuroDesk/neurocommand/commit/ff9ac994699bfa45a548da6fefda87574b3d8558

**Comment by stebo85** [comment]
oh cool! That's a very nice solution! much better than adding it to CVMFS :)
