### ISSUE TITLE
Is it possible to build container for Neurodesk on Mac, Windows?

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocontainers#97]
Hi all,

I'm trying to motivate as many people as possible to contribute containers to Neurodesk, and I just wonder: must one has a Linux machine for that? or can the containers be built on Mac or Windows?
I did a quick search and found this:
https://blog.jaimyn.dev/how-to-build-multi-architecture-docker-images-on-an-m1-mac/
so I guess it's possible, at least on Mac. The question if it's practical or not?
Has any of you had experience with that?

Best,
Oren

**Comment by aswinnarayanan** [comment]
Hi @civier. This architecture refers to the CPU architecture of the underlying machine, not specifically the OS.

The neurocontainers (and neurodesktop) should run on any Linux, Windows and Mac using a standard Intel or AMD cpu (x64, x86-64,  AMD64), via their respective installation of docker. (Technically, they all the docker engines run on linux, but this is taken care by the docker installation)

These images won't run on mobile chipsets like ARM (and Mac M1)
They will need images built using the multi-architectural build process outlined in the article.

**Comment by aswinnarayanan** [comment]
Oh ok. I've used Windows to build containers.
The neurocontainers require a Linux environment to run the builds scripts, so I used neurodesktop to run them scripts and generate the recipes. Then I built the docker image from the recipes in docker for windows for testing.

**Comment by stebo85** [comment]
Yes, you can build the containers on Mac or Windows as long as it is a x86_64 processor and not the new M1 chip, however it's easiest to build them on Linux or WSL2 as we wrote all scripts for it and it would need adjustments to make these work in native windows or mac.
